steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/livekit-agent:${_TAG}', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'gcr.io/$PROJECT_ID/livekit-agent:${_TAG}']

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: ['run', 'deploy', 'livekit-agent-service',
         '--image', 'gcr.io/$PROJECT_ID/livekit-agent:${_TAG}',
         '--region', '${_REGION}',
         '--platform', 'managed',
         '--allow-unauthenticated', # WARNING: Makes agent publicly accessible. Consider `--no-allow-unauthenticated` and IAM for production.
         '--port', '${PORT}',
         '--set-env-vars', 'PINECONE_API_KEY=${_PINECONE_API_KEY},COHERE_API_KEY=${_COHERE_API_KEY},PINECONE_ENVIRONMENT=${_PINECONE_ENVIRONMENT},PINECONE_INDEX_NAME=${_PINECONE_INDEX_NAME},PINECONE_NAMESPACE=${_PINECONE_NAMESPACE},GOOGLE_API_KEY=${_GOOGLE_API_KEY},LIVEKIT_URL=${_LIVEKIT_URL},LIVEKIT_API_KEY=${_LIVEKIT_API_KEY},LIVEKIT_API_SECRET=${_LIVEKIT_API_SECRET},LIVEKIT_SIP_URI=${_LIVEKIT_SIP_URI}', # All essential environment variables
         '--service-account', '${_SERVICE_ACCOUNT_EMAIL}', # IMPORTANT: This is now filled from your input.
         '--memory', '512Mi', # Adjust memory as needed
         '--cpu', '1',        # Adjust CPU as needed
         '--timeout', '300s', # Max request timeout. Adjust if agent needs more time to start/respond.
         '--concurrency', '80'] # Number of concurrent requests per instance.
  env:
  - 'PORT=8080' # Ensure this matches the PORT in Dockerfile and agent logic.

images:
- 'gcr.io/$PROJECT_ID/livekit-agent:${_TAG}'

substitutions:
  _TAG: 'latest' # Default image tag
  _REGION: 'us-central1' # Default GCP region. Change this to your preferred region.
  _PROJECT_ID: 'farmer-agent-466818' # Filled from gcloud init output
  _PINECONE_API_KEY: 'pcsk_6wiNh2_NVxQJXtDtMdc4TeFtgwSiT2nYzMBY57Rts51uJsdbzKTVLsP1FbjPzvjDnYZ1o6' # Filled from .env
  _COHERE_API_KEY: 'V5opD1DHzb3UKVKvL3ercfKYv5fqz4HA9ngiMd1d' # Filled from .env
  _PINECONE_ENVIRONMENT: 'us-east-1' # Filled from .env
  _PINECONE_INDEX_NAME: 'farmer-voice-index' # Filled from .env
  _PINECONE_NAMESPACE: 'farmer-rag' # Filled from .env
  _GOOGLE_API_KEY: 'AIzaSyBXnot3rhCxrt62KjsEfls2F4Sloy03j84' # Filled from .env
  _LIVEKIT_URL: 'wss://google-78a573z8.livekit.cloud' # Filled from .env
  _LIVEKIT_API_KEY: 'APIemzLJe7w652j' # Filled from .env
  _LIVEKIT_API_SECRET: 'QjzkY4eRs8YxOPo3mIkfEopXSKyDWdlXRa60NKD7YA' # Filled from .env
  _LIVEKIT_SIP_URI: 'sip:6xhhqxjqs9b.sip.livekit.cloud' # Filled from .env
  _SERVICE_ACCOUNT_EMAIL: 'farmer-agent-466818@appspot.gserviceaccount.com' # Filled from your service account input